# Generated by Django 5.0.7 on 2024-08-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_streamplatform_watchlist_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='watchlists', to='watchlist_app.streamplatform'),
        ),
    ]
