# Generated by Django 5.0.7 on 2024-08-11 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0003_watchlist_platforms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='platforms',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='platforms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlist_app.streamplatform', verbose_name=''),
        ),
    ]
